---
- name: Install PHP5-FPM
  sudo: yes
  apt:  package=php5-fpm state=latest

- name: Set Time Zone
  hosts: all
  gather_facts: False
  tasks:
    - name: Set timezone variables
      copy: content='Europe/London'
            dest=/etc/timezone
            owner=root
            group=root
            mode=0644
            backup=yes
      notify:
        - update timezone
  handlers:
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata