sportlobster_front_homepage:
    path:     /
    defaults: { _controller: SportlobsterFrontBundle:Home:index }

sportlobster_front_category:
    path:     /{category}
    defaults: { _controller: SportlobsterFrontBundle:Category:index }

sportlobster_front_category_type:
    path:     /{category}/{type}
    defaults: { _controller: SportlobsterFrontBundle:Category:type }
